# ~/.bashrc
# Interactive stuff, like alias's and PS1s etc

# .d folder style bashrc
# https://gist.github.com/bcomnes/5053fca2d7be573c0abd

#set -e
#set -x

run_scripts () {
  local script

  for script in $1/*; do

    # skip non-executable snippets and folders
    [ -f "$script" ] && [ -x "$script" ] || continue

    # execute $script in the context of the current shell
    source $script
  done
}

# bashrc folder
RCD=~/.rc.d
BASHRCD=~/.bashrc.d

# run all the settings
run_scripts "$RCD"
run_scripts "$BASHRCD"
