# ~/.bash_profile
#
# Non-interactive stuff like path, but just for bash!
# echo 'bash_profile'

#set -e
#set -x

# Source all sharable profile scripts
[[ -f ~/.profile ]] && source ~/.profile

# Also load .bashrc when logging in if running interactively
[[ -f ~/.bashrc && $- = *i* ]] && source ~/.bashrc
