#
# ~/.bash_profile
#
# Non-interactive stuff like path, but just for bash!
# echo 'bash_profile'

# Source all sharable profile scripts
[[ -f ~/.profile ]] && . ~/.profile

# Also load .bashrc when logging in
[[ -f ~/.bashrc ]] && . ~/.bashrc
