# ~/.zshrc
# Interactive stuff, like alias's and PS1s etc, just for ZSH

#set -e
#set -x

run_scripts () {
  local script

  for script in $1/*; do

    # skip non-executable snippets and folders
    [ -f "$script" ] && [ -x "$script" ] || continue

    # execute $script in the context of the current shell
    source $script
  done
}

# bashrc folder
RCD=~/.rc.d
ZSHRCD=~/.zshrc.d

# run all the settings
run_scripts "$RCD"
run_scripts "$ZSHRCD"

