ok brew
ok brew-tap homebrew/binary
ok brew-tap homebrew/boneyard
ok brew-tap homebrew/bundle
ok brew-tap homebrew/command-not-found
ok brew-tap homebrew/completions
ok brew-tap homebrew/core
ok brew-tap homebrew/dupes
ok brew-tap homebrew/services
ok brew-tap homebrew/versions
ok brew-tap caskroom/cask
ok brew-tap caskroom/fonts
ok brew-tap caskroom/versions
ok brew bash
ok brew bash-completion2
ok brew bork
ok brew ffmpeg
ok brew git
ok brew git-lfs
ok brew gnupg21
ok brew go
ok brew htop
ok brew keybase
ok brew lynx
ok brew mercurial
ok brew mobile-shell
ok brew node
ok brew pinentry-mac
ok brew python
ok brew python3
ok brew rsync
ok brew ruby
ok brew safe-rm
ok brew tmux
ok brew tree
ok brew vim
ok brew wget
ok brew youtube-dl
